name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3.0.0
      with:
        username: hnerno.o@gmail.com
        password: dckr_pat_YMOOtDryCC3lT93G8QvzEu08VJAs
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag kapi00z/test
    - name: Push the image
      run: docker image push kapi00z/test:latest
