name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ secrets.AZURE_REG }}
        username: ${{ secrets.AZURE_REG_LOGIN }}
        password: ${{ secrets.AZURE_REG_PASSWORD }}

    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        file: nginx/Dockerfile
        push: true
        tags: ${{ secrets.AZURE_REG }}/${{ secrets.AZURE_REG_LOGIN }}/nginx:latest